"""posts

Revision ID: 6c5eb00a1931
Revises: c402fcd599c3
Create Date: 2025-05-31 03:49:51.342867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6c5eb00a1931'
down_revision: Union[str, None] = 'c402fcd599c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('user_email_key'), 'user', type_='unique')
    op.drop_constraint(op.f('user_username_key'), 'user', type_='unique')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_unique_constraint('uq_user_email', 'user', ['email'])
    op.create_unique_constraint('uq_user_username', 'user', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_username', 'user', type_='unique')
    op.drop_constraint('uq_user_email', 'user', type_='unique')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_unique_constraint(op.f('user_username_key'), 'user', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('user_email_key'), 'user', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_table('post')
    # ### end Alembic commands ###
